language: php

php:
  - 7.2
  - 7.3

script: php tools/phpunit.phar tests --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
  - develop
