jobs:
  include:
    - stage: "Unit Tests"
      name: "Framework Tests"
      php:
        - 7.2
        - 7.3
      language: php
      services:
        - mysql
      script: php tools/phpunit.phar --configuration framework.xml.dist --coverage-clover=coverage.xml
    - script: php tools/phpunit.phar --configuration project.xml.dist --coverage-clover=coverage.xml
      php:
        - 7.2
        - 7.3
      language: php
      services:
        - mysql
      name: "Project Tests"

after_success:
- bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
  - develop

notifications:
  slack:
    rooms:
      - secure: b+hLjDD0H/fj3Fc+iUpEn1Hc8PSQjg3/Qp9dXMuF/WMCGGG5Jb5KiGBwNEM01oNv7zfcPaJyBIFvVF9kpHwF5qz/XZyfVcnxqr5pkL9PP4cbGgJfRvcwxTSE3gCLsF8j5uD4jSNFRqLxu5wEfPfNxGDz444bpQj53tSd19TK2N0wSf6Np8sQl7Bxdmkn33TBRswpZzeKj2oR5Tf2mFCLVwc0egfE987k02RHsJezB7rI3ubacHJ2t9bXEm/zptknUCLzWVuWsR1DlhfU3jqpgJTQMDkbL7uACG64rTYNxw3DGividIkCspP/YRQm+2ht6GRoAaeGDZ114V/dr/+5e5d21fT00zvmgugirjwn9E/cKwUYbbCEvze13qOFkGRLMl+P/hDGrxuaCfMBrQ4ptFvw+96pOUz1oLJeDHzOAuJ8AyFR1YVD742sr7ZXysZpWK09voyUa2Xb379MqvxdnaJBF9Mwzkz/XZjj0PNWUXYDSB0gkoJvQjH9qyGoUTNeK4TE4bylEPdPokQehPoK900BD1+j7CUegUS0ZpwcGJV3u8aq6cgdWAYPv0SOifWMgmffXousPe/XPMTNG5HVg0w3sryOUjYxDRvO7MyCrRZP6K+axoMEayCBlqEAXwweDHJ5Me4282rzOJqrLg7I2ORqMFaV8HROg/oZ6bteZME=
    on_success: always
    on_failure: always
